[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_flash_loan_tutorial = "4z55dAv3ySKCbDKUwG25cUbCyhNcqG7T5ze9aiYr4wpr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
